name: Laravel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: ls -a via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            ls -a
            cd repositories/Ticketing
            composer install
          host: ${{ secrets.HOST }}
          username: meednet1
          password: ${{ secrets.PASSWORD }}
          port: 	21098
